services:
  app:
    build: .
    container_name: radix_app
    ports:
    - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: radix_postgres
    environment:
      - POSTGRES_USER=radix
      - POSTGRES_PASSWORD=radix
      - POSTGRES_DB=radixdb
    volumes:
      - radix_pg3:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radix"]
      interval: 10s    
      timeout: 5s
      retries: 5
  frontend:
    image: carlos0406/front-radix
    container_name: radix_frontend
    ports:
    - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  radix_pg3:
    driver: local